---
# Mitum Ansible Inventory
# Generated: 2025-07-28T05:32:53Z
# Environment: production
# Nodes: 3

all:
  vars:
    # SSH Multiplexing Configuration
    ansible_ssh_common_args: '-o ControlMaster=auto -o ControlPersist=10m -o ControlPath=~/.ansible/cp/%h-%p-%r'
    ansible_ssh_pipelining: true
    
  children:
        bastion:
      hosts:
        bastion:
          ansible_host: 3.34.138.191
          ansible_user: ubuntu
                    ansible_ssh_private_key_file: "/Users/user/mitum_sit.pem"
                    public_ip: 3.34.138.191
          private_ip: 3.34.138.191
      vars:
        # Lower disk space requirement for bastion host
        min_disk_space_gb: 5
    
    mitum_nodes:
      hosts:
                node0:
          ansible_host: s
          mitum_node_id: 0
                    mitum_node_type: consensus
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4320
          private_ip: s
                node1:
          ansible_host: e
          mitum_node_id: 1
                    mitum_node_type: consensus
          mitum_api_enabled: false
                    mitum_api_port: 54320
          mitum_node_port: 4321
          private_ip: e
                node2:
          ansible_host: r
          mitum_node_id: 2
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4322
          private_ip: r
                node3:
          ansible_host: v
          mitum_node_id: 3
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4323
          private_ip: v
                node4:
          ansible_host: e
          mitum_node_id: 4
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4324
          private_ip: e
                node5:
          ansible_host: r
          mitum_node_id: 5
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4325
          private_ip: r
                node6:
          ansible_host: 0
          mitum_node_id: 6
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4326
          private_ip: 0
                node7:
          ansible_host: ,
          mitum_node_id: 7
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4327
          private_ip: ,
                node8:
          ansible_host: s
          mitum_node_id: 8
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4328
          private_ip: s
                node9:
          ansible_host: e
          mitum_node_id: 9
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4329
          private_ip: e
                node10:
          ansible_host: r
          mitum_node_id: 10
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4330
          private_ip: r
                node11:
          ansible_host: v
          mitum_node_id: 11
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4331
          private_ip: v
                node12:
          ansible_host: e
          mitum_node_id: 12
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4332
          private_ip: e
                node13:
          ansible_host: r
          mitum_node_id: 13
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4333
          private_ip: r
                node14:
          ansible_host: 1
          mitum_node_id: 14
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4334
          private_ip: 1
                node15:
          ansible_host: ,
          mitum_node_id: 15
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4335
          private_ip: ,
                node16:
          ansible_host: s
          mitum_node_id: 16
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4336
          private_ip: s
                node17:
          ansible_host: e
          mitum_node_id: 17
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4337
          private_ip: e
                node18:
          ansible_host: r
          mitum_node_id: 18
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4338
          private_ip: r
                node19:
          ansible_host: v
          mitum_node_id: 19
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4339
          private_ip: v
                node20:
          ansible_host: e
          mitum_node_id: 20
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4340
          private_ip: e
                node21:
          ansible_host: r
          mitum_node_id: 21
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4341
          private_ip: r
                node22:
          ansible_host: 2
          mitum_node_id: 22
                    mitum_node_type: api
          mitum_api_enabled: true
                    mitum_api_port: 54320
          mitum_node_port: 4342
          private_ip: 2
        
      vars:
        ansible_user: ubuntu
                        ansible_ssh_common_args: '-o ProxyJump=bastion -o ControlMaster=auto -o ControlPersist=10m -o ControlPath=~/.ansible/cp/%h-%p-%r'
                
        # Mitum configuration
        mitum_network_id: "mitum"
        mitum_model_type: "mitum-currency"
        mitum_environment: "production"
        
        # Network settings
        mitum_bind_host: "0.0.0.0"
        mitum_advertise_host: "{{ private_ip }}"
        
        # Consensus settings
        mitum_consensus_threshold: 100
        mitum_interval_broadcast_ballot: "1.5s"
        mitum_wait_broadcast_ballot: "5s"
        mitum_interval_broadcast_proposal: "5s"
        mitum_wait_broadcast_proposal: "10s"
        mitum_interval_broadcast_accept: "1.5s"
        mitum_wait_broadcast_accept: "5s"

        monitoring:
      hosts:
        monitor:
          ansible_host: 3.34.138.191
          ansible_user: ubuntu
      vars:
                # Monitor runs on bastion, so use bastion key and lower disk req.
        ansible_ssh_private_key_file: "/Users/user/mitum_sit.pem"
        min_disk_space_gb: 5
                prometheus_port: 9090
        grafana_port: 3000
        alertmanager_port: 9093
    
    mongodb:
      hosts:
                node0:
          ansible_host: s
                node1:
          ansible_host: e
                node2:
          ansible_host: r
                node3:
          ansible_host: v
                node4:
          ansible_host: e
                node5:
          ansible_host: r
                node6:
          ansible_host: 0
                node7:
          ansible_host: ,
                node8:
          ansible_host: s
                node9:
          ansible_host: e
                node10:
          ansible_host: r
                node11:
          ansible_host: v
                node12:
          ansible_host: e
                node13:
          ansible_host: r
                node14:
          ansible_host: 1
                node15:
          ansible_host: ,
                node16:
          ansible_host: s
                node17:
          ansible_host: e
                node18:
          ansible_host: r
                node19:
          ansible_host: v
                node20:
          ansible_host: e
                node21:
          ansible_host: r
                node22:
          ansible_host: 2
              vars:
        ansible_user: ubuntu
                        ansible_ssh_common_args: '-o ProxyJump=bastion -o ControlMaster=auto -o ControlPersist=10m -o ControlPath=~/.ansible/cp/%h-%p-%r'
         