---
all:
  children:
    bastion:
      hosts:
        bastion:
          ansible_host: 3.34.138.191
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/user/Desktop/mitum-ansible-deploy/mitum-ansible/keys/ssh/production/bastion.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    
    mitum_nodes:
      hosts:
        node0:
          ansible_host: 192.168.50.88
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/user/Desktop/mitum-ansible-deploy/mitum-ansible/keys/ssh/production/imfact-dev-01
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -i /Users/user/Desktop/mitum-ansible-deploy/mitum-ansible/keys/ssh/production/bastion.pem ubuntu@3.34.138.191"'
          mitum_node_id: 0
          mitum_node_port: 4320

        node1:
          ansible_host: 192.168.50.89
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/user/Desktop/mitum-ansible-deploy/mitum-ansible/keys/ssh/production/imfact-dev-01
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -i /Users/user/Desktop/mitum-ansible-deploy/mitum-ansible/keys/ssh/production/bastion.pem ubuntu@3.34.138.191"'
          mitum_node_id: 1
          mitum_node_port: 4321

        node2:
          ansible_host: 192.168.50.90
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/user/Desktop/mitum-ansible-deploy/mitum-ansible/keys/ssh/production/imfact-dev-01
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -i /Users/user/Desktop/mitum-ansible-deploy/mitum-ansible/keys/ssh/production/bastion.pem ubuntu@3.34.138.191"'
          mitum_node_id: 2
          mitum_node_port: 4322
          mitum_api_enabled: true
          mitum_api_port: 54320

      vars:
        mitum_network_id: "testnet"
        mitum_model_type: "mitum-currency"