---
# Configure Mitum nodes without installation

- name: Configure Mitum nodes
  hosts: mitum_nodes
  gather_facts: yes
  become: yes
  serial: "{{ configure_batch_size | default(5) }}"
  
  pre_tasks:
    - name: Verify Mitum is installed
      stat:
        path: "{{ mitum_install_dir }}/{{ mitum_model_type }}"
      register: mitum_installed
      failed_when: not mitum_installed.stat.exists
      
    - name: Backup current configuration
      archive:
        path: "{{ mitum_config_dir }}"
        dest: "{{ mitum_backup_dir }}/config-backup-{{ ansible_date_time.epoch }}.tar.gz"
        format: gz
      when: backup_before_configure | default(true)
      
  tasks:
    - name: Stop Mitum service
      systemd:
        name: "{{ mitum_service_name }}"
        state: stopped
      when: stop_during_configure | default(true)
      
    - name: Apply configuration
      include_role:
        name: mitum
        tasks_from: configure-nodes
      vars:
        mitum_deployment_phase: configure
        
    - name: Validate new configuration
      command: |
        {{ mitum_install_dir }}/{{ mitum_model_type }} validate-config \
          {{ mitum_config_dir }}/config.yml
      register: config_validation
      changed_when: false
      failed_when: 
        - config_validation.rc != 0
        - "'not implemented' not in config_validation.stderr"
        
    - name: Start Mitum service
      systemd:
        name: "{{ mitum_service_name }}"
        state: started
      when: stop_during_configure | default(true)
      
    - name: Wait for service to be ready
      wait_for:
        port: "{{ mitum_node_port }}"
        host: "{{ ansible_default_ipv4.address }}"
        state: started
        timeout: 60
        
    - name: Verify service health
      uri:
        url: "http://localhost:{{ mitum_node_port }}/v2/node"
        status_code: 200
      retries: 10
      delay: 3
      
  post_tasks:
    - name: Display configuration status
      debug:
        msg: |
          Configuration applied successfully!
          Node: {{ inventory_hostname }}
          Service: {{ mitum_service_name }}
          Config validation: {{ 'Passed' if config_validation.rc == 0 else 'Skipped' }}